### ISSUE TITLE
Upgrade Plan for angular 6

### ISSUE THREAD

**Issue by MRisto** [merlosy/ngx-material-file-input#2]
Do you plan to uprade this to angular 6?

**Comment by merlosy** [comment]
Yes, it is part of my plan.
For now, Angular is in rc6 and angular material in rc14. 
I'm waiting for official release to do the upgrade.

**Comment by MRisto** [comment]
Yeah can't wait till the full release

**Comment by MRisto** [comment]
I have an older Version of your Code from a plunker i think. For Version 6 i only needed to add shouldLabelFloat and remove on the fm.monitor the renderer2.

**Comment by merlosy** [comment]
Thanks for the tip.
I'm currently working on improving test coverage. It will make migration safer when the time will come to migrate
