### ISSUE TITLE
Bug when clear input

### ISSUE THREAD

**Issue by anafreitas** [merlosy/ngx-material-file-input#24]
I think there is a bug when you clear the input. If I remove a file and insert the same file again, the input doesn't accept it. This bug is present in the demo page.

**Comment by jbonet** [comment]
Very annoying bug. Any workaround?

**Comment by anafreitas** [comment]
Yes. I discovered that the file input is not being cleaned when you call the clear function, so I did this:

```
this.fileImage.clear();
this.fileImage._elementRef.nativeElement.children[0].value = null;
```

**Comment by jbonet** [comment]
Thanks, it worked like a charm

**Comment by merlosy** [comment]
Fix merged with https://github.com/merlosy/ngx-material-file-input/pull/26
