### ISSUE TITLE
Cancelling file upload dialog clear input values

### ISSUE THREAD

**Issue by JKancel** [merlosy/ngx-material-file-input#27]
Hi,

I encoutered an issue, when I'm closing the uploading file dialog whithout selected any files. If there was some files remaining from a previous selection. These one are all cleared.

Is it a normal behavior ?

Regards,

J.KANCEL

**Comment by merlosy** [comment]
Hi @JKancel , 
Clearing the files on cancel is the default behaviour in most browser except Firefox, you can verify [here](https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/file).
This is also a reason why I added the `clear` method to the component API.
