### ISSUE TITLE
Accepting multiple files [demo/docs improvement]

### ISSUE THREAD

**Issue by danieldanielecki** [merlosy/ngx-material-file-input#29]
Maybe it would be a good idea to show that you can also accept multiple formats in a form of array?

This is how I got it working, adding as a reference:
```
<ngx-mat-file-input formControlName="fileUploader"
          [accept]="['.doc', '.docx', '.jpg', '.jpeg', '.pdf', '.png', '.xls', '.xlsx']"
          placeholder="Accepted formats: DOC, DOCX, JPG, JPEG, PDF, PNG, XLS and XLSX, max files upload size: 20 MB."
          multiple>
</ngx-mat-file-input>
```

**Comment by merlosy** [comment]
I'll have a look.
Basically, it's the same as native file input i guess

**Comment by merlosy** [comment]
From the native [accept](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-accept) docs, it should be a `string`. Even though it seems to work for you, it may not work for some browsers.
