### ISSUE TITLE
Support for Angular 6 + RXJS 6

### ISSUE THREAD

**Issue by Tynarus** [merlosy/ngx-material-file-input#3]
Having issues using Angular 6. The first being RXJS imports being different, which is able to be avoided by importing the `rxjs-compat` package. 

The second issue when using ng6 is the following:

```
ERROR in node_modules/ngx-material-file-input/src/file-input/file-input.component.d.ts(7,22): error TS2720: Class 'FileInputComponent' incorrectly implements class 'MatFormFieldControl<FileInput>'. Did you mean to extend 'MatFormFieldControl<FileInput>' and inherit its members as a subclass?
  Property 'shouldLabelFloat' is missing in type 'FileInputComponent'.
```

Seems a new property was added in `MatFormFieldControl` that needs to be implemented within `FileInputComponent`.

**Comment by merlosy** [comment]
This project is based on [nrwl/nx](https://github.com/nrwl/nx) and they are under active development to support Angular 6 and RXJS 6. 
I will upgrade the lib through their CLI as soon as they're done.

BTW, you can try upgrading rxjs to v6 in your project with https://github.com/ReactiveX/rxjs-tslint

**Comment by jarro** [comment]
can get it working by manually for now by making the following change before compile.  

edit: 
node_modules/ngx-material-file-input/src/file-input/file-input.component.d.ts

add 
 `shouldLabelFloat: boolean;`

so it looks something like like.

```
export declare class FileInputComponent implements MatFormFieldControl<FileInput>, ControlValueAccessor, OnInit, OnDestroy {
    shouldLabelFloat: boolean;
    ngControl: NgControl;

```

**Comment by Tynarus** [comment]
@jarro already done, but good to document for others. Thank you!

**Comment by Tynarus** [comment]
@merlosy looks like https://github.com/nrwl/nx has been upgraded to NG 6 as of a few days ago. :)

**Comment by Tynarus** [comment]
Aye, if I thought it would be that simple I'd fork and submit a PR hahah. There's always something!

**Comment by Smiter15** [comment]
Any news on this ?

**Comment by andrewinkler1** [comment]
any update?

**Comment by merlosy** [comment]
It's still a work in progress.
Basically it works, it's just about changes in running test, project config and packaging that changed with the new version of nx and angular

**Comment by merlosy** [comment]
Migration done!
For version with angular 6 -> see 0.2.0
