### ISSUE TITLE
Improve documentation FileValidator

### ISSUE THREAD

**Issue by danieldanielecki** [merlosy/ngx-material-file-input#30]
Please add to the demo that the following import `import { FileValidator } from 'ngx-material-file-input';` is required.

**Comment by idzer0lis** [comment]
Also about maxSize from the docs...if its in bites, bytes, mb, whatever.

**Comment by merlosy** [comment]
@idzer0lis It definitely won't be in bites :). The existing pipe itself is called `byteFormat`, if you think it lacks a `bitFormat` pipe, please open another issue.

**Comment by merlosy** [comment]
@danieldanielecki I'm adding it to the demo app, in the form validation section. Sorry for the delay
