### ISSUE TITLE
Allow Files (*.*)

### ISSUE THREAD

**Issue by danieldanielecki** [merlosy/ngx-material-file-input#31]
It seems to me it might be out of scope for this dependency, but is there a way to disable "Allow Files (*.*)"? Basically right now user can simply choose this from a dropdown once a pop up with files to upload will appear and upload anything she/he wants. The only way to reject the unwanted files is by making Angular's validations on the front-end side for files with endings on specific file names and/or back-end once the file is being uploaded?

**Comment by merlosy** [comment]
The [accept attribute](https://www.w3schools.com/tags/att_input_accept.asp) is supported and may do the job.
