### ISSUE TITLE
Files with long name exceed input's width

### ISSUE THREAD

**Issue by subotin94** [merlosy/ngx-material-file-input#33]

**Comment by merlosy** [comment]
can you provide a reproduction example?

**Comment by jlzor** [comment]
Files with long name exceed input's width, an Example:

![error](https://user-images.githubusercontent.com/12281413/67993480-4a666400-fbfe-11e9-89e6-d0fa5f793e44.png)

**Comment by merlosy** [comment]
@jlzor thanks for reporting the issue.
I'll hide text overflow and put some ellipsis (...).

**Comment by merlosy** [comment]
@subotin94 @jlzor Do you have some time to check if the PR fixes the issue?
It seems so on my side, but a second opinion is always appreciated :)

**Comment by subotin94** [comment]
I will check it in the next few weeks. Thank you @merlosy

**Comment by anthonyrivas** [comment]
@merlosy Just pulled this, and can confirm it fixes the issue on my end as well.
