### ISSUE TITLE
Support for Angular Material 8

### ISSUE THREAD

**Issue by teusemanuel** [merlosy/ngx-material-file-input#34]
Have a plan to add support for angular material 8?

**Comment by merlosy** [comment]
Hi! I do. I've just been busy lately but i'll get to it soon

**Comment by pangjianxin** [comment]
+1

**Comment by Gemorroj** [comment]
https://github.com/Vrael/ngx-material-file-input/commit/1400a8b2dc07a04fa5e1cb02f17c4a367243f1c2

**Comment by bbortt** [comment]
@Gemorroj are you planning to include it into the main repository?

**Comment by Gemorroj** [comment]
@bbortt it's not my repo)
ping @Vrael

**Comment by bbortt** [comment]
Uhh yeah.. my bad. Anyways, it would be a useful update 👍

**Comment by danieldanielecki** [comment]
+1

**Comment by bbortt** [comment]
cherry-picked https://github.com/Vrael/ngx-material-file-input/commit/1400a8b2dc07a04fa5e1cb02f17c4a367243f1c2 into a pr -> #36

**Comment by Gemorroj** [comment]
@merlosy any news?

**Comment by Vrael** [comment]
Hi! I didn't PR changes because automated test failed.
I noticed Travis uses nodejs 8.16.0 but on my local works fine with 10.16.0.

**Comment by bbortt** [comment]
The error is:
> You are running version v8.16.0 of Node.js, which is not supported by Angular CLI 8.0+.
The official Node.js version that is supported is 10.9 or greater.
I will update the PR.

**Comment by bbortt** [comment]
Build passing now. Thx to @kvloover..

**Comment by abouroubi** [comment]
Any news on this ?

**Comment by bbortt** [comment]
pr is ready, I've tagged the owner. No feedback so far.
