### ISSUE TITLE
Demo does not work with IE11

### ISSUE THREAD

**Issue by yglodt** [merlosy/ngx-material-file-input#35]
Hello,

the demo https://merlosy.github.io/ngx-material-file-input/ does not work in IE11 with the following error:

![image](https://user-images.githubusercontent.com/489599/59087506-1b74ec00-8905-11e9-8bad-4dc62f0e5173.png)

Maybe it's just a matter of enabling the polyfills.

**Comment by merlosy** [comment]
Did you try with ES6 polyfills?

**Comment by yglodt** [comment]
It works definately with the polyfills in my Angular projet. This issue was about the fact that the demo does not work with IE 11.
