### ISSUE TITLE
demo 

### ISSUE THREAD

**Issue by nhhockeyplayer** [merlosy/ngx-material-file-input#4]
can a demo app be made that shows end to end 

ingesting a file into back end
and rendering that file back to UI

**Comment by merlosy** [comment]
The purpose of this library is not to provide an end to end solution to upload your files. It is oriented to provide a visual component to manage smoothly the user experience. It integrates with angular material forms, and it's up to you to manage what happen when you submit the form containing the file.
If you want to retrieve your files, i can suggest you the Filesaver lib.

For questions regarding architecture choices in your solution, i also suggest you to post your issue on stackoverflow, with details about your environment and expectations.
