### ISSUE TITLE
cant be use in angular 9

### ISSUE THREAD

**Issue by keyone2693** [merlosy/ngx-material-file-input#49]
can u update the code to use it in angular 9

**Comment by zimo85** [comment]
I am updating material via ng update @angular/material, but I cannot complete the process, receiving this error:
 Package "ngx-material-file-input" has an incompatible peer dependency to "@angular/material" (requires "^8.1.1", would install "9.0.0").

I have already updated the ngx-material-file-input to 2.1.0 version

**Comment by Void-0** [comment]
Same here. There are some breaking changes in v9 related to imports from Angular and Angular material where you need to target more specific import paths now, meaning any v8 angular projects / components will need to be updated.

**Comment by merlosy** [comment]
Would this fit your needs? https://github.com/merlosy/ngx-material-file-input/blob/master/libs/material-file-input/package.json

**Comment by keyone2693** [comment]
problems are with the new way of importing angular material

**Comment by merlosy** [comment]
@keyone2693 Can you be more specific about your issue? Is it just a matter is peer dependency definition or is there anything else blocking you from using it, as of version 2.1.0?

**Comment by zimo85** [comment]
> Would this fit your needs? https://github.com/merlosy/ngx-material-file-input/blob/master/libs/material-file-input/package.json

Yes, now it works.

**Comment by nikitka** [comment]
Could you please release new version with updated peer dependencies?

**Comment by jzgoda** [comment]
@merlosy, would you be able to bump the version on NPM to the latest master w/ the fixed peer dependency issue?

**Comment by merlosy** [comment]
fixed with [2.1.1](https://github.com/merlosy/ngx-material-file-input/tree/v2.1.1)
