### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by hellmark1990** [merlosy/ngx-material-file-input#55]
@angular/core:  8.2.14
ngx-material-file-input: 2.1.1

`EROR in node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(31,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(38,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(39,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(40,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(41,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(42,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/file-input/file-input.component.d.ts(50,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/model/file-input.model.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
node_1   | node_modules/ngx-material-file-input/lib/model/file-input.model.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.`

**Comment by mugambiwarwema** [comment]
@hellmark1990 

Any word on this error or an alternative package I can use for file uploads?

**Comment by bsh314** [comment]
Same issue here. It seems like compatibility issue with TS version

**Comment by suhasghodke** [comment]
> @hellmark1990
> 
> Any word on this error or an alternative package I can use for file uploads?

Use previous version, i am doing the same.

**Comment by mugambiwarwema** [comment]
@suhasghodk was right.

I downgraded(uninstalled) version 2.1.1 and Installed version 2.1.0

npm uninstall ngx-material-file-input

npm i ngx-material-file-input@2.1.0

Now all is well

**Comment by raframil** [comment]
I got the same problem with @angular/core: ~8.2.14 and ngx-material-file-input: ^2.1.1

**Comment by raframil** [comment]
I got the same problem with 2.1.1, downgrade to 2.1.0 solved it for me

**Comment by oallauddin** [comment]
Ran into same error. You can try this.
https://www.npmjs.com/package/@angular-material-components/file-input
