### ISSUE TITLE
Adding opportunity to use this lib for dynamic reactive driven forms

### ISSUE THREAD

**Issue by wild2999** [merlosy/ngx-material-file-input#7]
Hello!
Thank you very much for this useful angular package!

I faced a problem that this lib cannot work with dynamic formControlName `[formControlName]`.
Can you add please this opportunity?

Thanks.

**Comment by merlosy** [comment]
@wild2999 It IS already working with model driven form.
I invite you to have a look at the demo site i set up: https://merlosy.github.io/ngx-material-file-input/

Please let me know if there are any missing bits in the docs.
