### ISSUE TITLE
ngx-material-file-input can't be used with Angular 11

### ISSUE THREAD

**Issue by Leccho** [merlosy/ngx-material-file-input#75]
Upgrading from Angular 10 to 11, I get this error:
`Package "ngx-material-file-input" has an incompatible peer dependency to "@angular/common" (requires "^8.1.3 || ^9.0.0" (extended), would install "11.1.1").`

Is there a plan to fix this issue?

**Comment by Leccho** [comment]
It seems to work fine as of now, I deleted the packages for the upgrade and re-installed the packages after. I'd still like to see support to the latest angular version!

**Comment by naviln** [comment]
+1 would really like this

**Comment by desertSniper87** [comment]
@Leccho What are you doing for workaround? I am using Angular 11 and getting this:

**Comment by Leccho** [comment]
I deleted the `ngx-material-file-input` packages. You might wanna remove the `node_modules` folder. Then I use `npm install` to reinstall `node_modules`. Once installed I used `ng upgrade` to get version 11. Then I reinstalled `ngx-material-file-input`.

**Comment by naviln** [comment]
> I deleted the `ngx-material-file-input` packages. You might wanna remove the `node_modules` folder. Then I use `npm install` to reinstall `node_modules`. Once installed I used `ng upgrade` to get version 11. Then I reinstalled `ngx-material-file-input`.

Tried this, and worked! haha. thanks.
