### ISSUE TITLE
Error when adding "multiple" properties in Angular 12

### ISSUE THREAD

**Issue by marquinmpfs** [merlosy/ngx-material-file-input#85]
Adding the "multiple" property to ngx-mat-file-input generates the following error:

![image](https://user-images.githubusercontent.com/10059932/125149531-f10f4180-e10f-11eb-8bcd-8e161539246b.png)

![image](https://user-images.githubusercontent.com/10059932/125149548-fff5f400-e10f-11eb-9ccd-579569c502b6.png)

**Comment by PapaNappa** [comment]
Since `multiple` is a boolean property … have you tried `[multiple]="true"`?

**Comment by marquinmpfs** [comment]
Resolved
